# Changes to workflow name require changes to badge URL in README.md
name: Make Video

on:
  push:

jobs:
  make-video:
    # Platform recommended in cypress-io/github-action docs.
    runs-on: ubuntu-16.04
    env:
      # Use native docker command within docker-compose
      COMPOSE_DOCKER_CLI_BUILD: 1
      # Use buildkit to speed up docker command
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: patcon/editly
          ref: docker-containerized-cli
          path: editly

      - name: Build app via docker-compose
        working-directory: editly
        run: docker-compose up --detach

      - name: Generate the video
        run: |
          docker cp my-video.json5 editly:/outputs
          cd editly
          docker-compose run editly bash -c "editly /outputs/my-video.json5 --out /outputs/my-video.mp4"
          mkdir generated
          docker cp editly:/outputs/my-video.mp4 ./generated/

      - uses: actions/upload-artifact@v2
        if : success()
        with:
          name: my-video
          path: editly/generated/*

      # For eventually running cypress for screenshots and video footage.
      - uses: actions/checkout@v2
        with:
          repository: pol-is/polis
          ref: dev
          path: polis
